package models.enums

enum class SignUpStates {
    EMAIL_VALIDATION,
    EMAIL_OTP_VALIDATION,
    IQAMA_VALIDATION,
    IQAMA_OTP_VALIDATION,
    MOBILE_VALIDATION,
    MOBILE_OTP_VALIDATION,
    PASSWORD_VALIDATION,
    SIGN_UP_SUCCESSFULLY
}